version: "3.8"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - db_env_file
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql
  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:4000
    env_file:
      - api_env_file
    volumes:
      - ./api:/src
    ports:
      - "4000:4000"
    depends_on:
      - db

  
volumes:
  database:

