# Generated by Django 4.0.4 on 2022-05-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('other_names', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=255, null=True)),
                ('road_name', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('county', models.CharField(max_length=255, null=True)),
                ('postcode', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('date_shipped', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_delivered', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(default='')),
                ('long_description', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('developer', models.CharField(max_length=255)),
                ('developer_logo_url', models.CharField(default='', max_length=2083)),
                ('image_url', models.CharField(max_length=2083)),
                ('release_date', models.DateField(null=True)),
                ('age_rating', models.CharField(default='18+', max_length=255)),
                ('category', models.CharField(default='action', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPlatform',
            fields=[
                ('product_platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('is_featured', models.BooleanField(default=False)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='api.platform')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product1', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('isSold', models.BooleanField(default=False)),
                ('product_platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='api.productplatform')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_play', models.IntegerField(null=True)),
                ('social', models.IntegerField(null=True)),
                ('graphics', models.IntegerField(null=True)),
                ('value', models.IntegerField(null=True)),
                ('overall', models.IntegerField(null=True)),
                ('date_reviewed', models.DateTimeField(auto_now_add=True)),
                ('positive', models.TextField(default='')),
                ('negative', models.TextField(default='')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='api.order')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stock')),
            ],
        ),
    ]
