# Generated by Django 4.0.3 on 2022-04-25 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_review_date_reviewed_review_review_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='developer_id',
        ),
        migrations.AddField(
            model_name='product',
            name='developer',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='developer',
                to='api.developer'),
            preserve_default=False,
        ),
    ]
