# Generated by Django 4.0.4 on 2022-05-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_review_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer', to='api.productplatform'),
        ),
        migrations.AlterField(
            model_name='productplatform',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.product'),
        ),
    ]
