# Generated by Django 4.0.4 on 2022-05-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review_product_platform_and_more'),
        ('api', '0006_stock_issold_alter_order_date_delivered_and_more'),
    ]

    operations = [
    ]
