# Generated by Django 4.0.3 on 2022-05-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_developer_id_product_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgenre',
            name='id',
        ),
        migrations.AddField(
            model_name='productgenre',
            name='product_genre_id',
            field=models.AutoField(default='default', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productgenre',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='api.genre'),
        ),
        migrations.AlterField(
            model_name='productgenre',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='api.product'),
        ),
        migrations.AlterField(
            model_name='productplatform',
            name='platform_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='api.platform'),
        ),
        migrations.AlterField(
            model_name='productplatform',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='api.product'),
        ),
    ]
