# Generated by Django 4.0.4 on 2022-05-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stock_issold_alter_order_date_delivered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productplatform',
            old_name='platform_id',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='productplatform',
            old_name='product_id',
            new_name='product',
        ),
    ]
