# Generated by Django 4.0.4 on 2022-05-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_platform_id_productplatform_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productplatform',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
