# Generated by Django 4.0.3 on 2022-05-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_productgenre_id_productgenre_product_genre_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgenre',
            name='product_genre_id',
        ),
        migrations.AddField(
            model_name='productgenre',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
