# Generated by Django 4.0.4 on 2022-05-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_is_featured_alter_productplatform_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='productplatform',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
