# Generated by Django 4.0.4 on 2022-05-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_product_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgenre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='productgenre',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='age_rating',
            field=models.CharField(default='18+', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='action', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='developer',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='ProductGenre',
        ),
    ]
