# Generated by Django 4.0.4 on 2022-05-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_productgenre_genre_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='game_play',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='graphics',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='negative',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='overall',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='positive',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='social',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(default=''),
        ),
    ]
