# Generated by Django 4.0.4 on 2022-05-13 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_review_rating_remove_review_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_platform_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='api.productplatform'),
        ),
    ]
