# Generated by Django 4.0.4 on 2022-05-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_review_rating_remove_review_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.AddField(
            model_name='product',
            name='developer_logo_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
