# Generated by Django 4.0.4 on 2022-05-13 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_delete_developer_alter_stock_product_platform_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
