# Generated by Django 4.0.4 on 2022-05-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_customer_address_remove_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
