name: Deploy Backend 
on:
  push:
    branches:
      - main
    paths:
      - "api/**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: be1containerregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker build ./api -t be1containerregistry.azurecr.io/titleone:${{ github.sha }}
          docker push be1containerregistry.azurecr.io/titleone:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "titleone"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "be1containerregistry.azurecr.io/titleone:${{ github.sha }}"
